# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20495d76514056af4aaff4e0e90699e2e433261e4a024492e7fb3a774068d55389f6372620b4ca2e73165a4837e92b0ef6d4064712333082e2a6fe634228a601

test:
  secret_key_base: d720e119e67c448d1819c7678d73e4e56fa8703e63cc45d952551470ca413436de914d56cd41032f70626efb8a8a3615f13279d93505fb4068b09a45c040df6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
