# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c2775102e1196904c81ce48e2b3178c5b6e543868789ed223b2a720433173c3f8110264d467ac61af67fc145e4e3975a9a1199e1c882be6c1cbebde71eee719

test:
  secret_key_base: 29c43f545c1be7f31d13a2aa553f93e6e5a6edf6c5efb643ed87b3e5deecd83c1305abb3746b384692b274ea9b524b65f363c4b9b6de8c28d2111096883878f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
